### ISSUE TITLE
Fails to parse unicode in captions

### ISSUE THREAD

**Issue by EricThrift** [aaren/pandoc-reference-filter#9]
The function replace_references() throws an error if the figure captions contain any non-ascii characters. This seems to be the case even with quotation marks, dashes and the like, which are converted by the `--smart` option in pandoc.

```
File "build/bdist.linux-i686/egg/internalreferences/internalreferences.py", line 236, in figure_replacement
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 7: ordinal not in range(128)
pandoc: Error running filter internal-references
```

**Comment by aaren** [comment]
That's a hassle. Can you give me an example input and usage that causes this?

**Comment by aaren** [comment]
ok, it's any figure with a unicode containing caption and attributes:

```
!["ä"](image){fig:ref}
```

**Comment by aaren** [comment]
@EricThrift can you try out the latest on master? I think I've fixed it. Will reopen if there is a problem.

You can pip install directly from github like this:

```
pip install git+https://github.com/aaren/pandoc-reference-filter.git
```

**Comment by EricThrift** [comment]
It works!

**Comment by aaren** [comment]
Glad to hear it :)

I've possibly missed unicode somewhere else - just let me know if you find anything else.
